env:
  node: true
  browser: true
  es6: true
  es2021: true
  es2022: true
ignorePatterns:
  - disc/
extends:
  - eslint:recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  indent:
    - 2
    - 4
  linebreak-style:
    - 2
    - windows
  quotes:
    - 2
    - double
  semi:
    - 2
    - always
  no-var:
    - 2
  comma-dangle:
    - 2
    - always-multiline
  no-unused-vars: warn
  spaced-comment:
    - 2
  linebreak-style:
    - 0
    - windows