env:
  node: true
  browser: true
  es6: true
  es2021: true
  es2022: true
ignorePatterns:
  - disc/
extends:
  - eslint:recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  indent:
    - 2
    - 4
    - SwitchCase: 1
  quotes:
    - 2
    - double
  quote-props:
    - 2
    - as-needed
    - unnecessary: true
  semi:
    - 2
    - always
  linebreak-style:
    - 0
    - windows
  spaced-comment:
    - 2
  comma-dangle:
    - 2
    - always-multiline
  no-var:
    - 2
  no-unused-vars:
    - 1
    - varsIgnorePattern: ^_
  no-redeclare:
    - 2
  no-const-assign:
    - 2
  no-unneeded-ternary:
    - 2
  prefer-const:
    - 2
  prefer-arrow-callback:
    - 2
  prefer-object-spread:
    - 1
  dot-notation:
    - 1
  eqeqeq:
    - 2
    - smart
  no-else-return:
    - 2
  no-unneeded-ternary:
    - 1
  logical-assignment-operators:
    - 2